import type { Metadata } from "next";
import { Inter, IBM_Plex_Sans_KR } from "next/font/google";
import "../styles/globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-inter',
});
const ibm = IBM_Plex_Sans_KR({
  weight: ["500","600","700"],
  display: 'swap',
  variable: '--font-ibm',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${ibm.variable}`}>
      <body>{children}</body>
    </html>
  );
}
